### ISSUE TITLE
Fails when Installing on a Mac

### ISSUE THREAD

**Issue by timseed** [sganis/minirepo#2]
I just installed the project, both times in a brand new VirtualEnv (Python 2.7) - on a Mac.

First time I used the PIP mechanism - the 2nd Time I pulled your GIT Repo 

Alas - same error.... Not sure if it is not a MAC Issue... as it is occurring in the MultiProcessor calls....

The error is

> /******** Minirepo ********/
> extensions      = [u'bz2', u'egg', u'gz', u'tgz', u'whl', u'zip']
> package_types   = [u'bdist_egg', u'bdist_wheel', u'sdist']
> processes       = 1
> python_versions = [u'3.4', u'py34']
> repository      = /Users/tim/minirepo
> Using config file /Users/tim/.minirepo 
> Traceback (most recent call last):
>   File "/Users/tim/pymirror/bin/minirepo", line 9, in <module>
>     load_entry_point('minirepo==1.0.3', 'console_scripts', 'minirepo')()
>   File "build/bdist.macosx-10.11-x86_64/egg/minirepo.py", line 290, in main
>   File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
>     return Pool(processes, initializer, initargs, maxtasksperchild)
>   File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 159, in __init__
>     self._repopulate_pool()
>   File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 214, in _repopulate_pool
>     for i in range(self._processes - len(self._pool)):
> TypeError: unsupported operand type(s) for -: 'unicode' and 'int'

**Comment by timseed** [comment]
Sorry for the Bandwidth - this is a MAC Issue (stupid stupid MAC) ....

Works lovely on Ubuntu 14 ....

Thanks for your work/effort

Tim
